### ISSUE TITLE
MasterMind - retour sur la spécification fonctionnelle

### ISSUE THREAD

**Issue by Seefy** [ThomasPerche/CVETicTacToe#1]
@ThomasPerche 
Après première lecture de votre spécification fonctionnelle, nous souhaiterions clarifier certains points:
- Pourriez-vous ajouter un objectif du jeu ? nous aimerions être certain de bien cerner le but du jeu, qui manque jusqu'ici de clarté
- Dans la partie "Suite des cas d'utilisation 1 et  2, possibilités du jeu" : pouvez-vous spéficier vos attentes quant à l'implémentation de possibilités de jeu ? c'est-à-dire, comment doit-on spéficier "rien à signaler", "bonne couleur mal placée" et "bonne couleur bien placée" ?

Cordialement,
L'équipe technique.

**Comment by Alekz936** [comment]
Pour ce qui s'agit du déroulement du jeu, nos spécifications décrivent tout les cas scénarique possible du jeu. Cependant, pour ce qui est des réponses suite à une proposition du joueur devin (Rien à signaler, bonne couleur mais mauvaise position et bonne couleur et bonne position) vous pourrez les implémenter de la manière dont vous souhaiter à la seule condition que les joueurs soit informés de la situation du jeu à un instant T, après un essai du devin.
Pourquoi pas, par exemple un code affiché aux utilisateurs à chaque début de partie.
Si votre choix est flexible et maintnenable, nous sommes ouvert à toute possibilité tant que les utilisateurs sache le résultat des essais.
