### ISSUE TITLE
MASTERMIND - Scenarios possibles manquants

### ISSUE THREAD

**Issue by killwithabass** [ThomasPerche/CVETicTacToe#2]
Il semble manquer des scénarios dans votre besoin.
Vous faites la différenciation entre une bonne réponse bien placée et une bonne réponse mal placée mais aucune différenciation n'est faite pour plusieurs bonnes réponses.

Ne serait-il pas nécessaire d'afficher à chaque fois un message du type : 
"X bonnes réponses dont X bien placées."

**Comment by Alekz936** [comment]
Oui effectivement, c'est une bonne idée, vous pouvez le concevoir comme ca.
