### ISSUE TITLE
Remarques

### ISSUE THREAD

**Issue by ViBiOh** [ThomasPerche/CVETicTacToe#3]
# Remarques
## MOA
- Essayez au maximum d'éviter l'utilisation de balises HTML dans un Markdown. Les `<blockquote>` peuvent être remplacées par des `>`, pareil pour les `<li>` -> `*`
- Vous répétez beaucoup de fois "Un message l'informe de cela.", je pense que vous pouvez reformuler la phrase pour que cela soit plus fluide à lire.
## MOE
- Bon début sur les spécifications techniques, à poursuivre
- Préférez parler de la classe Accueil plutôt que de `Accueil.class`
## Code
- Attention à ne pas faire une _god-class_ avec `Accueil.java`
- Eviter d'utiliser les `sysout` directement dans le code, inspirez vous du cours ;)
- Pensez aux tests
## Git
- Aucune utilisation des commentaires dans git, vous indiquez juste quel fichier vous mettez à jour sur les commit sans préciser la nature des modifications.
- Attention à vos fichiers de configuration d'IDE sur le repo `.classpath`, `.project`. Vous pouvez utilisez mieux votre `.gitignore`.

**Comment by Alekz936** [comment]
Avancement :
* MOA : Modifications faites
* MOE : Modifications faites - Reste à continuer les specifications.
* Code : Ajout du code avancé - SysOut à Modifier - Tests à établir avec le groupe
* Git : Prise en compte de l'utilisation de GitHub. A modifier sur cette voie.

**Comment by ViBiOh** [comment]
# CVETicTacToe

Ranger un peu le git, à quoi correspondent les deux `.md` à la racine ? Ce sont des documents reçus à mettre dans MOE.

MOA
 
"scnéarios" -> "scénarios"
Pas de scénarios de recettes ?

Dans les spécifications ne pas faire la distinction entre Interface et Implémentation. La description de l'interface doit déduire son implémentation, bien sinon.
Pourquoi préfixer vos variables ou classes avec une lettre en minuscule ?

**Comment by Alekz936** [comment]
#####Ranger un peu le git, à quoi correspondent les deux .md à la racine ? Ce sont des documents reçus à mettre dans MOE.
Modifié

####MOA
#####"scnéarios" -> "scénarios"
Modifié 

#####Pas de scénarios de recettes ?
A prévoir

#####Dans les spécifications ne pas faire la distinction entre Interface et Implémentation. La description de l'interface doit déduire son implémentation, bien sinon.
Modifié

#####Pourquoi préfixer vos variables ou classes avec une lettre en minuscule ?
Modifié
